MVC4ManyToMany/MVC4ManyToMany/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC4ManyToMany.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = @"Your course registration system. Use the ""User Profile Page"" below to add users to the system.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Course registration system.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Contact me using the details here.";

            return View();
        }
    }
}

MVC4ManyToMany/MVC4ManyToMany/Controllers/UserProfileController.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web.Mvc;

using MVC4ManyToMany.Models.ViewModels;
using MVC4ManyToManyDatabase;
using MVC4ManyToManyDomain;

namespace MVC4ManyToMany.Controllers
{
    public class UserProfileController : Controller
    {
        private readonly MVC4ManyToManyContext db = new MVC4ManyToManyContext();

        public ActionResult Index()
        {
            var userProfiles = db.UserProfiles.ToList();
            var userProfileViewModels = userProfiles.Select(userProfile => userProfile.ToViewModel()).ToList();

            return View(userProfileViewModels);
        }

        public ActionResult Create()
        {
            var userProfileViewModel = new UserProfileViewModel { Courses = PopulateCourseData() };

            return View(userProfileViewModel);
        }

        [HttpPost]
        public ActionResult Create(UserProfileViewModel userProfileViewModel)
        {
            if (ModelState.IsValid)
            {
                var userProfile = userProfileViewModel.ToDomainModel();
                AddOrUpdateCourses(userProfile, userProfileViewModel.Courses);
                db.UserProfiles.Add(userProfile);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(userProfileViewModel);
        }

        public ActionResult Edit(int id = 0)
        {
            // Get all courses
            var allDbCourses = db.Courses.ToList();

            // Get the user we are editing and include the courses already subscribed to
            var userProfile = db.UserProfiles.Include("Courses").FirstOrDefault(x => x.UserProfileID == id);
            var userProfileViewModel = userProfile.ToViewModel(allDbCourses);

            return View(userProfileViewModel);
        }

        [HttpPost]
        public ActionResult Edit(UserProfileViewModel userProfileViewModel)
        {
            if (ModelState.IsValid)
            {
                var originalUserProfile = db.UserProfiles.Find(userProfileViewModel.UserProfileID);

                // Add or update new courses
                // AddOrUpdateCourses(originalUserProfile, userProfileViewModel.Courses);

                // Add or update courses keeping original
                AddOrUpdateKeepExistingCourses(originalUserProfile, userProfileViewModel.Courses);
                
                db.Entry(originalUserProfile).CurrentValues.SetValues(userProfileViewModel);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(userProfileViewModel);
        }

        public ActionResult Details(int id = 0)
        {
            // Get all courses
            var allDbCourses = db.Courses.ToList();

            // Get the user we are editing and include the courses already subscribed to
            var userProfile = db.UserProfiles.Include("Courses").FirstOrDefault(x => x.UserProfileID == id);
            var userProfileViewModel = userProfile.ToViewModel(allDbCourses);

            return View(userProfileViewModel);
        }

        public ActionResult Delete(int id = 0)
        {
            var userProfileIQueryable = from u in db.UserProfiles.Include("Courses")
                                  where u.UserProfileID == id
                                  select u;

            if (!userProfileIQueryable.Any())
            {
                return HttpNotFound("User not found.");
            }

            var userProfile = userProfileIQueryable.First();
            var userProfileViewModel = userProfile.ToViewModel();

            return View(userProfileViewModel);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var userProfile = db.UserProfiles.Include("Courses").Single(u => u.UserProfileID == id);
            DeleteUserProfile(userProfile);

            return RedirectToAction("Index");
        }

        private void DeleteUserProfile(UserProfile userProfile)
        {
            if (userProfile.Courses != null)
            {
                foreach (var course in userProfile.Courses.ToList())
                {
                    userProfile.Courses.Remove(course);
                }
            }

            db.UserProfiles.Remove(userProfile);
            db.SaveChanges();
        }

        private ICollection<AssignedCourseData> PopulateCourseData()
        {
            var courses = db.Courses;
            var assignedCourses = new List<AssignedCourseData>();

            foreach (var item in courses)
            {
                assignedCourses.Add(new AssignedCourseData
                {
                    CourseID = item.CourseID,
                    CourseDescription = item.CourseDescripcion,
                    Assigned = false
                });
            }

            return assignedCourses;
        }

        private void AddOrUpdateCourses(UserProfile userProfile, IEnumerable<AssignedCourseData> assignedCourses)
        {
            if (assignedCourses == null) return;

            if (userProfile.UserProfileID != 0)
            {
                // Existing user - drop their existing courses and add the new ones if any
                foreach (var course in userProfile.Courses.ToList())
                {
                    userProfile.Courses.Remove(course);
                }

                foreach (var course in assignedCourses.Where(c => c.Assigned))
                {
                    userProfile.Courses.Add(db.Courses.Find(course.CourseID));
                }
            }
            else
            {
                // New user
                foreach (var assignedCourse in assignedCourses.Where(c => c.Assigned))
                {
                    var course = new Course { CourseID = assignedCourse.CourseID };
                    db.Courses.Attach(course);
                    userProfile.Courses.Add(course);
                }                
            }
        }

        private void AddOrUpdateKeepExistingCourses(UserProfile userProfile, IEnumerable<AssignedCourseData> assignedCourses)
        {
            var webCourseAssignedIDs = assignedCourses.Where(c => c.Assigned).Select(webCourse => webCourse.CourseID);
            var dbCourseIDs = userProfile.Courses.Select(dbCourse => dbCourse.CourseID);
            var courseIDs = dbCourseIDs as int[] ?? dbCourseIDs.ToArray();
            var coursesToDeleteIDs = courseIDs.Where(id => !webCourseAssignedIDs.Contains(id)).ToList();

            // Delete removed courses
            foreach (var id in coursesToDeleteIDs)
            {
                userProfile.Courses.Remove(db.Courses.Find(id));
            }

            // Add courses that user doesn't already have
            foreach (var id in webCourseAssignedIDs)
            {
                if (!courseIDs.Contains(id))
                {
                    userProfile.Courses.Add(db.Courses.Find(id));
                }            
            }
        }
    }
}

MVC4ManyToMany/MVC4ManyToMany/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1><br />
    <h3>@ViewBag.Message</h3>
</hgroup>

<article>
    <p>
        Add / edit / delete users and register them for available courses.
    </p>
</article>

<aside>
    <h3>Links</h3>
    <p>
        Navigate the application using these links.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

MVC4ManyToMany/MVC4ManyToMany/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Personal:</span>
        <span><a href="mailto:cbruen1@yahoo.com">cbruen1 (at) yahoo (dot) com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Twitter</h3>
    </header>
    <p>
        <span><a href="http://twitter.com/CiaranBruen">http://twitter.com/CiaranBruen</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>LinkedIn</h3>
    </header>
    <p>
        <span><a href="http://www.linkedin.com/in/ciaranbruen">http://www.linkedin.com/in/CiaranBruen</a></span>
    </p>
</section>

MVC4ManyToMany/MVC4ManyToMany/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1><br />
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                To learn more about me visit
                <a href="http://www.linkedin.com/in/ciaranbruen" title="Ciaran Bruen">http://www.linkedin.com/in/ciaranbruen</a>.
                The page features my <mark>work and education history</mark> as well as other details and interests.
            </p>
        </div>
    </section>
}

<h4>Get started by clicking here to go to the User Profile page:</h4>
<p>
	@Html.ActionLink("User Profile Page", "Index", "UserProfile")
</p>

<h3>Some details about this project:</h3>
<ol class="round">
    <li class="one">
        <h5>Developed in ASP.NET MVC4</h5>
        ASP.NET MVC gives us a powerful, patterns-based way to build dynamic websites that
        enables a clean separation of concerns and that gives you full control over markup
        for enjoyable, agile development. ASP.NET MVC includes many features that enable
        fast, TDD-friendly development for creating sophisticated applications that use
        the latest web standards.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245151">Learn more…</a>
    </li>

    <li class="two">
        <h5>Uses Entity Framework Code First approach</h5>
        Entity Framework Code First is an ORM tool that allows rapid database development where the model is defined in code.
        <a href="http://msdn.microsoft.com/en-us/data/jj193542.aspx">Learn more…</a>
    </li>

    <li class="three">
        <h5>CRUD functionality</h5>
        Fully working CRUD (CReate /Update / Delete) application allowing us to add, edit, and delete records from our app.
    </li>
</ol>